import type { Metadata } from "next";
import Script from "next/script";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import "./resume.min.css";

import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive" // Ensures it runs after the page loads
        />
        {/* Place children where you want to render a page or nested layout */}
        <main>{children}</main>
        <Analytics />
      </body>
    </html>
  );
}
